---
# prerequisites
- name: Install libraries
  become: True
  become_user: "{{ root_user }}"
  apt:
      name: "{{ item }}"
      state: latest
      update_cache: True
  with_items:
    - build-essential
    - gfortran
    - openmpi-bin
    - libopenmpi-dev
    - libfftw3-dev
    - libfftw3-mpi-dev
    - liblapack-dev
    - libblas-dev

# Will only download once
- name: Get Quantum ESPRESSO source
  get_url:
    url: "{{ quantum_espresso_url }}"
    dest: "{{ quantum_espresso_code_folder }}/{{  quantum_espresso_src_archive }}"
  register: quantum_espresso_download

# For some reason this is not idempotent on travis
# See also https://github.com/ansible/ansible/issues/22254
# (but not sure it is related)
- name: Extract QE source
  unarchive:
    src: "{{ quantum_espresso_download.dest }}"
    dest: "{{ quantum_espresso_code_folder }}"
    remote_src: yes
  when: quantum_espresso_download.changed

# --fpe-summary=none removes all floating-point exceptions
# see https://github.com/marvel-nccr/quantum-mobile/issues/52
- name: Configure QE
  shell: "FFLAGS='-O3 -g -ffpe-summary=none' ./configure --enable-parallel"
  args:
    creates: "{{ quantum_espresso_topdir }}/make.inc"
    chdir: "{{ quantum_espresso_topdir }}"
     
# this is needed because aiida isn't yet able to parse
# the new XML format
- name: "Force to use old XML format"
  lineinfile:
    path: "{{ quantum_espresso_topdir }}/make.inc"
    insertafter: "DFLAGS         =  -D__FFTW3 -D__MPI"
    line: "DFLAGS        +=  -D__OLDXML"


- name: Make QE executables
  shell: "make {{ item.name }}"
  args:
    creates: "{{ quantum_espresso_topdir }}/bin/{{ item }}.x"
    chdir: "{{ quantum_espresso_topdir }}"
  with_items: "{{ quantum_espresso_executables }}"
  register: quantum_espresso_make

- import_tasks: tests.yml
  when: quantum_espresso_make.changed and run_tests is defined and run_tests

- name: "Put a line in ${HOME}/.profile to add QE to the path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export PATH=${PATH}:{{ quantum_espresso_topdir }}/bin"

- include_role:
    name: release_notes
  vars:
    section: "Quantum ESPRESSO"
    option: "version"
    value: "{{ quantum_espresso_version }}"
  when: release_notes is defined and release_notes

- include_role:
    name: release_notes
  vars:
    section: "Quantum ESPRESSO"
    option: "usage"
    value: >-
        Quantum ESPRESSO is installed in {{ quantum_espresso_topdir }}. 
        'pw.x', 'cp.x', ... have been added to the PATH
  when: release_notes is defined and release_notes

- name: Clean object files
  shell: "rm {{ quantum_espresso_topdir }}/*/src/*.o"
  when: clean is defined and clean
